from movie_page import movie_page
from user_page import user_page
from article_page import article_page
from celebrity_page import celebrity_page
from director_page import director_page
from category_page import category_page
from follow_page import follow_page
from download_page import download_page
from bt_page import bt_page
from recommend_page import recommend_page